AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  Region:
    Type: String
    Default: 'us-east-1'
  CFNCustomProvider:
    Type: String
  CopyFunction:
    Type: String
  SubDomain:
    Type: String
  CreateApex:
    Type: String
  CreateDns:
    Type: String
  HostedZoneId:
    Type: String

Conditions:
  CreateApexConfig:  !Equals 
    - !Ref CreateApex
    - 'yes'
  CreateDnsConfig:  !Equals
    - !Ref CreateDns
    - 'yes'

Resources:
  CopyCustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !Ref CopyFunction

  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - - Ref: DomainName
          - Ref: AWS::NoValue
      Region: !Ref Region
      ValidationMethod: DNS
      DomainValidationOptions:
        Fn::If:
          - CreateDnsConfig
          - - DomainName: !Sub '${SubDomain}.${DomainName}'
              HostedZoneId: !Ref HostedZoneId
          - Ref: AWS::NoValue
Outputs:
  # DNSRecord:
  #   Description: DNS record
  #   Value: !Sub '${CertificateDNSRecord.Name} ${CertificateDNSRecord.Type} ${CertificateDNSRecord.Value}'

  CertificateArn: 
    Description: Issued certificate
    Value: !Ref Certificate
